#services:
#  db:
#    container_name: postgresss
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: postgres-0
#      POSTGRES_PASSWORD: springlibrarydeme
#      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5332:5432"
#    networks:
#      - db
#    restart: unless-stopped
#
#networks:
#  db:
#    driver: bridge
#volumes:
#  db: